language: c++

dist: trusty
sudo: false

#https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#  {
#    "alias": "r-packages-trusty",
#    "sourceline": "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/",
#    "key_url": "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x51716619E084DAB9"
#  },

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - lcov
      - r-base
      - r-base-dev

install:
  - sudo R --slave --vanilla -e "install.packages('Rcpp', repos='http://cran.case.edu')"

script:
  - cd lhs_nb
  - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release # Test release build options
  - cmake --build build
  - ./build/lhstest/lhstest
  - cmake . -Bcoveragebuild -DCMAKE_BUILD_TYPE=Coverage # Test debug build and coverage options
  - cmake --build coveragebuild
  - ./coveragebuild/lhstest/lhstest

after_success:
  - cd coveragebuild
  - lcov --directory lhstest --capture --output-file lhstest.info
  - lcov --remove lhstest.info 'lhstest/*' '/usr/*' --output-file lhstest.clean.info
  - lcov --list lhstest.clean.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
 
